name: ci-cd
on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t danielaag5/app:${{ github.sha }} .
      - run: docker push danielaag5/app:${{ github.sha }}
      - run: kubectl set image deployment/web-deployment web=danielaag5/app:${{ github.sha }}
        continue-on-error: true