name: ci-cd
on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login a Docker Hub
        run: echo "${{ secrets.dckr_pat_dV57FE9TaFktqp7LofQZFJ3JYok }}" | docker login -u "${{ secrets.danielaag5 }}" --password-stdin
      - run: docker build -t danielaag5/inventario-app:${{ github.sha }} .
      - run: docker push danielaag5/inventario-app:${{ github.sha }}

      - continue-on-error: true
        run: kubectl set image deployment/web-deployment web=danielaag5/inventario-app:${{ github.sha }}